package com.trading.common.events;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.io.Serializable;
import java.math.BigDecimal;
import java.time.Instant;
import java.util.Map;
import java.util.UUID;

/**
 * Trade signal event generated by strategy engine
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class TradeSignalEvent implements Serializable {
    private static final long serialVersionUID = 1L;

    private String signalId;
    private String strategyId;
    private String strategyName;
    private String symbol;
    private String exchange;
    private SignalType signalType;
    private BigDecimal price;
    private BigDecimal quantity;
    private BigDecimal confidence;
    private TradingMode tradingMode;
    private boolean requiresApproval;
    private String userId;
    private Map<String, Object> parameters;
    private Instant timestamp;

    public enum SignalType {
        BUY, SELL
    }

    public enum TradingMode {
        MANUAL, SEMI_AUTOMATED, AUTOMATED
    }
}

